# Generated by Django 4.2.5 on 2023-10-01 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('suc_chua', models.IntegerField()),
                ('loai_ban', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DsDatBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trang_thai', models.BooleanField(default=False)),
                ('so_dien_thoai', models.CharField(default=False, max_length=10)),
                ('thoi_gian_nhan_ban', models.DateTimeField(default=False)),
                ('thoi_gian_dat_ban', models.DateTimeField(default=False)),
                ('so_luong_ban', models.IntegerField()),
                ('ten_nguoi_dat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GiamGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('ty_le_giam', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('so_tien_giam', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonCocTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thanh_toan', models.DateTimeField(default=django.utils.timezone.now)),
                ('tong_tien', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_gia', models.FloatField()),
                ('link_anh', models.ImageField(upload_to='upload/menu')),
                ('ten_san_pham', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_thanh_toan', models.DateTimeField(default=django.utils.timezone.now)),
                ('tong_tien', models.FloatField()),
                ('giam_gia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lagu.giamgia')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lagu.khachhang')),
                ('menus', models.ManyToManyField(related_name='ds_mon_an', to='lagu.menu')),
            ],
        ),
        migrations.AddConstraint(
            model_name='giamgia',
            constraint=models.CheckConstraint(check=models.Q(('ty_le_giam__isnull', True), ('so_tien_giam__isnull', True), _connector='OR'), name='one_field_only'),
        ),
        migrations.AddField(
            model_name='dsorder',
            name='ds_dat_ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagu.dsdatban'),
        ),
        migrations.AddField(
            model_name='dsorder',
            name='hoa_don_coc_tien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_hoa_don_coc_tien', to='lagu.hoadoncoctien'),
        ),
        migrations.AddField(
            model_name='dsorder',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagu.menu'),
        ),
        migrations.AddField(
            model_name='dsdatban',
            name='ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagu.ban'),
        ),
        migrations.AddField(
            model_name='dsdatban',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lagu.khachhang'),
        ),
        migrations.AddField(
            model_name='dsdatban',
            name='menus',
            field=models.ManyToManyField(through='lagu.DsOrder', to='lagu.menu'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='hoa_don',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagu.hoadonthanhtoan'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagu.menu'),
        ),
    ]
