# Generated by Django 4.2.5 on 2023-10-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0002_ban_chitiethoadon_dsdatban_dsorder_giamgia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='loai',
            field=models.CharField(choices=[('mon_nuoc', 'Mon Nuoc'), ('mon_an', 'Mon An'), ('trang_mien', 'Trang Mien')], default='mon_an', max_length=10),
        ),
    ]
