# Generated by Django 4.2.5 on 2023-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0003_menu_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_trang_thai',
            field=models.BooleanField(default=True),
        ),
    ]
