# Generated by Django 4.2.5 on 2023-10-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0005_alter_dsdatban_so_dien_thoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='hoa_don_coc_tien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ds_hoa_don_coc_tien', to='lagu.hoadoncoctien'),
        ),
    ]
