# Generated by Django 4.2.5 on 2023-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0006_alter_dsorder_hoa_don_coc_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadoncoctien',
            name='trang_thai',
            field=models.CharField(choices=[('đã thanh toán', 'Da Thanh Toan'), ('chưa thanh toán', 'Chua Thanh Toan'), ('hoàn tiền', 'Hoan Tien'), ('hủy cọc', 'Huy Coc')], default='chưa thanh toán', max_length=50),
        ),
    ]
