# Generated by Django 4.2.5 on 2023-10-08 04:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0007_hoadoncoctien_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsorder',
            name='hoa_don_coc_tien',
        ),
        migrations.AddField(
            model_name='hoadoncoctien',
            name='ds_dat_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lagu.dsdatban'),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 11, 8, 27, 649581)),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='trang_thai',
            field=models.CharField(choices=[('chưa thanh toan', 'Chua Thanh Toan'), ('đã thanh toán', 'Da Thanh Toan'), ('huy_coc', 'Huy Coc')], default='chưa thanh toan', max_length=100),
        ),
    ]
