# Generated by Django 4.2.5 on 2023-10-08 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0008_remove_dsorder_hoa_don_coc_tien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ds_dat_ban',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lagu.dsdatban'),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 11, 9, 1, 408154)),
        ),
    ]
