# Generated by Django 4.2.5 on 2023-10-08 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0010_alter_hoadoncoctien_ds_dat_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsdatban',
            name='thoi_gian_dat_ban',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dsdatban',
            name='thoi_gian_nhan_ban',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 11, 40, 51, 111513)),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='trang_thai',
            field=models.CharField(choices=[('da thanh toan', 'Da Thanh Toan'), ('huy coc', 'Huy Coc'), ('hoan coc', 'Hoan Coc')], default='da thanh toan', max_length=100),
        ),
    ]
