# Generated by Django 4.2.5 on 2023-10-08 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0011_alter_dsdatban_thoi_gian_dat_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ds_dat_ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagu.dsdatban', unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 11, 43, 4, 594031)),
        ),
    ]
