# Generated by Django 4.2.5 on 2023-10-09 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0015_alter_giamgia_ma_giam_gia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 18, 54, 58, 642855)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='loai',
            field=models.CharField(choices=[('mon_nuoc', 'Mon Nuoc'), ('mon_an', 'Mon An'), ('trang_mieng', 'Trang Mien')], default='mon_an', max_length=20),
        ),
    ]
