# Generated by Django 4.2.5 on 2023-10-09 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0017_alter_hoadoncoctien_ngay_thanh_toan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 22, 9, 7, 735128)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link_anh',
            field=models.ImageField(default=None, upload_to='upload/menu'),
        ),
    ]
