# Generated by Django 4.2.5 on 2023-10-11 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0019_alter_hoadoncoctien_ngay_thanh_toan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giamgia',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='giamgia',
            name='so_luong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 19, 20, 24, 182170)),
        ),
    ]
