# Generated by Django 4.2.5 on 2023-10-11 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0020_giamgia_active_giamgia_so_luong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default='N0G5V1', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 19, 45, 25, 100955)),
        ),
    ]
