# Generated by Django 4.2.5 on 2023-10-11 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0022_dsdatban_thoi_gian_nhan_dat_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsdatban',
            name='thoi_gian_nhan_dat_ban',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 21, 33, 10, 219968)),
        ),
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default='JG2RDE', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 21, 33, 10, 219968)),
        ),
    ]
