# Generated by Django 4.2.5 on 2023-10-11 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0023_alter_dsdatban_thoi_gian_nhan_dat_ban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsdatban',
            name='thoi_gian_nhan_dat_ban',
        ),
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default='L0J67C', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 22, 7, 39, 422920)),
        ),
    ]
