# Generated by Django 4.2.5 on 2023-10-11 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0024_remove_dsdatban_thoi_gian_nhan_dat_ban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsdatban',
            name='Ma_dat_ban',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default='A85BH6', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 22, 18, 40, 616519)),
        ),
    ]
