# Generated by Django 4.2.5 on 2023-10-11 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0025_dsdatban_ma_dat_ban_alter_giamgia_ma_giam_gia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsdatban',
            name='Ma_dat_ban',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default='9OU597', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 22, 19, 11, 539513)),
        ),
    ]
