# Generated by Django 4.2.5 on 2023-10-12 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0028_hoadonthanhtoan_ma_hoa_don_alter_giamgia_ma_giam_gia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default='EIIJFH', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 7, 32, 58, 951945)),
        ),
    ]
