# Generated by Django 4.2.5 on 2023-10-16 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0032_alter_giamgia_ma_giam_gia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='is_trang_thai',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default='RBLFJX', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 9, 51, 32, 127718)),
        ),
    ]
