# Generated by Django 4.2.5 on 2023-10-19 15:54

import datetime
from django.db import migrations, models
import lagu.models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0033_ban_is_trang_thai_alter_giamgia_ma_giam_gia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giamgia',
            name='ma_giam_gia',
            field=models.CharField(blank=True, default=lagu.models.generate_random_code, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 22, 54, 49, 332612)),
        ),
    ]
