# Generated by Django 4.2.5 on 2023-10-20 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0034_alter_giamgia_ma_giam_gia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='loai_ban',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 8, 12, 12, 456082)),
        ),
    ]
