# Generated by Django 4.2.5 on 2023-10-20 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0035_alter_ban_loai_ban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadonthanhtoan',
            name='menus',
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 20, 45, 41, 835702)),
        ),
    ]
