# Generated by Django 4.2.5 on 2023-10-20 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0036_remove_hoadonthanhtoan_menus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 21, 7, 10, 582281)),
        ),
        migrations.AlterField(
            model_name='hoadonthanhtoan',
            name='ma_hoa_don',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
