# Generated by Django 4.2.5 on 2023-10-20 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0037_alter_hoadoncoctien_ngay_thanh_toan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadonthanhtoan',
            name='menus',
            field=models.ManyToManyField(related_name='ds_mon_an', to='lagu.menu'),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 21, 42, 55, 237664)),
        ),
        migrations.AlterField(
            model_name='hoadonthanhtoan',
            name='ma_hoa_don',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
