# Generated by Django 4.2.5 on 2023-10-21 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0039_alter_hoadoncoctien_ngay_thanh_toan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 0, 22, 41, 994188)),
        ),
        migrations.AlterField(
            model_name='hoadonthanhtoan',
            name='menus',
            field=models.ManyToManyField(related_name='ds_mon_an', through='lagu.ChiTietHoaDon', to='lagu.menu'),
        ),
    ]
