# Generated by Django 4.2.5 on 2023-10-21 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0041_remove_hoadonthanhtoan_menus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadonthanhtoan',
            name='menus',
            field=models.ManyToManyField(related_name='ds_mon_an', to='lagu.menu'),
        ),
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 0, 24, 32, 250119)),
        ),
    ]
